name: spydoorman-soundboard
description: discord soundboard
runtime:
  name: nodejs
  options:
    packagemanager: yarn
config:
  pulumi:tags:
    value:
      pulumi:template: container-azure-typescript
