name: Deploy

on:
  push:
    branches:
      - master

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  migrate-database:
    name: Migrate database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn --pure-lockfile
      - name: Run migrations
        working-directory: projects/mongo
        run: yarn run up
        env:
          MIGRATIONS_CONNECTION_URI: ${{ secrets.MIGRATIONS_CONNECTION_URI }}

  deploy-bot:
    name: Deploy bot
    needs: migrate-database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn --pure-lockfile
      - name: Deploy Bot
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: stuckinab0x/dev
          work-dir: projects/infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
